version: '{branch}-{build}'

environment:
  matrix:
    # Tip: sed -nre 's|.*Qt/.*/|    - QTDIR: &|p' | tr '/' '\' | sort -nt. -k1.20,1 -k2,2 -k3
    - QTDIR: C:\Qt\5.10.1\msvc2013_64
    - QTDIR: C:\Qt\5.10.1\msvc2015
    - QTDIR: C:\Qt\5.10.1\msvc2015_64

configuration:
  - debug
  - release

install:
  - git submodule update --init --recursive
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2017=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - qmake -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - '%make%'

  # Build the installer
  #- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  #- ISCC /Q qmaketravis.iss

after_build:
  - if [%CONFIGURATION%]==[release] (
    windeployqt %CONFIGURATION%\sentryTest.exe --dir distrib &&
    cp %CONFIGURATION%\sentryTest.exe distrib &&
    7z a -y %CONFIGURATION%-distrib.zip distrib &&
    appveyor PushArtifact %CONFIGURATION%-distrib.zip
    )