version: '{branch}-{build}'

environment:
  matrix:
  - arch: x64
    qt: 5.10.1
    cc: VS2017
    mode: release
    QTDIR: C:\Qt\5.10.1\msvc2017_64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


configuration:
  - debug
  - release

install:
  - git submodule update --init --recursive
  - set vcarch=%arch%
  - if "%arch%" == "x64" set vcarch=amd64
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %vcarch%
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QTDIR=%QTDIR%
  
before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - qmake -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - '%make%'

  # Build the installer
  #- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  #- ISCC /Q qmaketravis.iss

after_build:
  - if [%CONFIGURATION%]==[release] (
    windeployqt %CONFIGURATION%\sentryTest.exe --dir distrib &&
    cp %CONFIGURATION%\sentryTest.exe distrib &&
    cp %CONFIGURATION%\sentryTest.pdb distrib &&
    7z a -y %CONFIGURATION%-distrib.zip distrib &&
    appveyor PushArtifact %CONFIGURATION%-distrib.zip
    )